In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

In [2]:
# IMDB-Movies-Data.csv
base_url = 'https://gist.githubusercontent.com/alti-tude/710cb9d4dfc7ebcd0afb9cf93d8f6a8d/raw/574730ba009e69b81d6c79f2fef2c3dd5145db0a/'

In [3]:
data = {
    'apples':[3,2,0,1],
    'oranges':[0,3,7,2]
}

In [4]:
purchases = pd.DataFrame(data)
purchases.head()

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [12]:
purchases.set_index(np.array(['June','Robert','Lily','David']))

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [9]:
df = pd.read_csv(base_url+'purchases.csv')

df.head()

  Unnamed: 0  apples  oranges
0       June       3        0
1     Robert       2        3
2       Lily       0        7
3      David       1        2

In [11]:
df = pd.read_csv(base_url+'purchases.csv',index_col=0)

df.head()

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [13]:
df = pd.read_json(base_url+'purchases.json')

df.head()

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [16]:
movies_df = pd.read_csv(base_url+'IMDB-Movie-Data.csv',index_col='Title')

In [17]:
movies_df.head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [20]:
movies_df.describe

<bound method NDFrame.describe of                          Rank                     Genre  \
Title
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi
Prometheus                  2  Adventure,Mystery,Sci-Fi
Split                       3           Horror,Thriller
Sing                        4   Animation,Comedy,Family
Suicide Squad               5  Action,Adventure,Fantasy
...                       ...                       ...
Secret in Their Eyes      996       Crime,Drama,Mystery
Hostel: Part II           997                    Horror
Step Up 2: The Streets    998       Drama,Music,Romance
Search Party              999          Adventure,Comedy
Nine Lives               1000     Comedy,Family,Fantasy

                                                               Description  \
Title
Guardians of the Galaxy  A group of intergalactic criminals are forced ...
Prometheus               Following clues to the origin of mankind, a te...
Split                    Three girls are kidnapped by a man with a diag...
Sing                     In a city of humanoid animals, a hustling thea...
Suicide Squad            A secret government agency recruits some of th...
...                                                                    ...
Secret in Their Eyes     A tight-knit team of rising investigators, alo...
Hostel: Part II          Three American college students studying abroa...
Step Up 2: The Streets   Romantic sparks occur between two dance studen...
Search Party             A pair of friends embark on a mission to reuni...
Nine Lives               A stuffy businessman finds himself trapped ins...

                                     Director  \
Title
Guardians of the Galaxy            James Gunn
Prometheus                       Ridley Scott
Split                      M. Night Shyamalan
Sing                     Christophe Lourdelet
Suicide Squad                      David Ayer
...                                       ...
Secret in Their Eyes                Billy Ray
Hostel: Part II                      Eli Roth
Step Up 2: The Streets             Jon M. Chu
Search Party                   Scot Armstrong
Nine Lives                   Barry Sonnenfeld

                                                                    Actors  \
Title
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...
...                                                                    ...
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...

                         Year  Runtime (Minutes)  Rating   Votes  \
Title
Guardians of the Galaxy  2014                121     8.1  757074
Prometheus               2012                124     7.0  485820
Split                    2016                117     7.3  157606
Sing                     2016                108     7.2   60545
Suicide Squad            2016                123     6.2  393727
...                       ...                ...     ...     ...
Secret in Their Eyes     2015                111     6.2   27585
Hostel: Part II          2007                 94     5.5   73152
Step Up 2: The Streets   2008                 98     6.2   70699
Search Party             2014                 93     5.6    4881
Nine Lives               2016                 87     5.3   12435

                         Revenue (Millions)  Metascore
Title
Guardians of the Galaxy              333.13       76.0
Prometheus                           126.46       65.0
Split                                138.12       62.0
Sing                                 270.32       59.0
Suicide Squad                        325.02       40.0
...                                     ...        ...
Secret in Their Eyes                    NaN       45.0
Hostel: Part II                       17.54       46.0
Step Up 2: The Streets                58.01       50.0
Search Party                            NaN       22.0
Nine Lives                            19.64       11.0

[1000 rows x 11 columns]>

In [21]:
movies_df.tail()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [22]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Genre               1000 non-null   object
 2   Description         1000 non-null   object
 3   Director            1000 non-null   object
 4   Actors              1000 non-null   object
 5   Year                1000 non-null   int64
 6   Runtime (Minutes)   1000 non-null   int64
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 133.8+ KB

In [24]:
movies_df.shape

(1000, 11)

In [25]:
temp_df = movies_df.append(movies_df)

In [27]:
temp_df.shape

(2000, 11)

In [26]:
temp_df.drop_duplicates()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [28]:
movies_df.rename(columns={
    'Revenue (Millions)':'revenue_millions',
    'Runtime (Minutes)':'runtime'
})

,Rank,Genre,Description,Director,Actors,Year,runtime,Rating,Votes,revenue_millions,Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [29]:
movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [30]:
movies_df.columns = ['rank','genre','description','director','actors','year','runtime','rating','votes','revenue_millions','metascore']
movies_df.head()

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [31]:
movies_df.isna()

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,False,False,False,False,False,False,False,False,False,False,False
Prometheus,False,False,False,False,False,False,False,False,False,False,False
Split,False,False,False,False,False,False,False,False,False,False,False
Sing,False,False,False,False,False,False,False,False,False,False,False
Suicide Squad,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,False,False,False,False,False,False,False,False,False,True,False
Hostel: Part II,False,False,False,False,False,False,False,False,False,False,False
Step Up 2: The Streets,False,False,False,False,False,False,False,False,False,False,False
Search Party,False,False,False,False,False,False,False,False,False,True,False
Nine Lives,False,False,False,False,False,False,False,False,False,False,False

In [32]:
movies_df.dropna()

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Resident Evil: Afterlife,994,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
Project X,995,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [33]:
revenue_df = movies_df['revenue_millions']

In [34]:
revenue_df.fillna(revenue_df.mean())

Title
Guardians of the Galaxy    333.130000
Prometheus                 126.460000
Split                      138.120000
Sing                       270.320000
Suicide Squad              325.020000
                              ...
Secret in Their Eyes        82.956376
Hostel: Part II             17.540000
Step Up 2: The Streets      58.010000
Search Party                82.956376
Nine Lives                  19.640000
Name: revenue_millions, Length: 1000, dtype: float64

In [37]:
prom = movies_df.loc['Prometheus']
prom

rank                                                                2
genre                                        Adventure,Mystery,Sci-Fi
description         Following clues to the origin of mankind, a te...
director                                                 Ridley Scott
actors              Noomi Rapace, Logan Marshall-Green, Michael Fa...
year                                                             2012
runtime                                                           124
rating                                                              7
votes                                                          485820
revenue_millions                                               126.46
metascore                                                          65
Name: Prometheus, dtype: object

In [38]:
prom = movies_df.iloc[1]
prom

rank                                                                2
genre                                        Adventure,Mystery,Sci-Fi
description         Following clues to the origin of mankind, a te...
director                                                 Ridley Scott
actors              Noomi Rapace, Logan Marshall-Green, Michael Fa...
year                                                             2012
runtime                                                           124
rating                                                              7
votes                                                          485820
revenue_millions                                               126.46
metascore                                                          65
Name: Prometheus, dtype: object

In [39]:
movies_df.iloc[1:4]

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [40]:
movies_df.loc['Prometheus':'Sing']

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [42]:
movies_df[movies_df['director'] == 'Ridley Scott']

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
The Martian,103,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
Robin Hood,388,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
American Gangster,471,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
Exodus: Gods and Kings,517,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0
The Counselor,522,"Crime,Drama,Thriller",A lawyer finds himself in over his head when h...,Ridley Scott,"Michael Fassbender, Penélope Cruz, Cameron Dia...",2013,117,5.3,84927,16.97,48.0
A Good Year,531,"Comedy,Drama,Romance",A British investment broker inherits his uncle...,Ridley Scott,"Russell Crowe, Abbie Cornish, Albert Finney, M...",2006,117,6.9,74674,7.46,47.0
Body of Lies,738,"Action,Drama,Romance",A CIA agent on the ground in Jordan hunts down...,Ridley Scott,"Leonardo DiCaprio, Russell Crowe, Mark Strong,...",2008,128,7.1,182305,39.38,57.0

In [43]:
movies_df[movies_df['rating']>=8.6].head()

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
Kimi no na wa,97,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.0
Dangal,118,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN

In [47]:
movies_df[movies_df['genre'].str.contains('Drama')]

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
Hidden Figures,12,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
Colossal,15,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
Hacksaw Ridge,17,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
...,...,...,...,...,...,...,...,...,...,...,...
Selma,990,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
Take Me Home Tonight,993,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0

In [50]:
movies_df[
    (movies_df['rating']>=8.6)
    &(movies_df['revenue_millions']>=movies_df['revenue_millions'].quantile(0.25))
]

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore
Title,,,,,,,,,,,
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0

In [51]:
def rating_function(x):
    return 'good' if x>=8.0 else 'bad'

In [54]:
movies_df['rating category'] = movies_df['rating'].apply(rating_function)
movies_df

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore,rating category
Title,,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,good
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,bad
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,bad
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,bad
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,bad
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,bad
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,bad
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,bad
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,bad

In [55]:
movies_df['rating category'] = movies_df['rating'].apply(lambda x: 'good' if x>=8.0 else 'bad')
movies_df

,rank,genre,description,director,actors,year,runtime,rating,votes,revenue_millions,metascore,rating category
Title,,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,good
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,bad
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,bad
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,bad
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,bad
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,bad
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,bad
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,bad
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,bad

# Task

In [58]:
music_df = pd.read_csv(base_url+'MusicTop50.csv',index_col=0)
music_df.head()

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability..db..,Loudness..,Liveness.,Valence (),Length,Acousticness,Speechiness,Popularity
1,Se�orita,Shawn Mendes,canadian pop,117.0,55.0,76,-6,8.0,75.0,191.0,4,3,79.0
2,China,Anuel AA,reggaeton flow,105.0,81.0,79,-4,8.0,61.0,302.0,8,9,92.0
3,boyfriend (with Social House),Ariana Grande,dance pop,190.0,80.0,40,-4,16.0,70.0,186.0,12,46,85.0
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93.0,65.0,64,-8,8.0,55.0,198.0,12,19,86.0
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,NaN,65.0,58,-4,11.0,18.0,175.0,45,7,94.0

In [59]:
music_df.tail()

,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability..db..,Loudness..,Liveness.,Valence (),Length,Acousticness,Speechiness,Popularity
46,One Thing Right,Marshmello,brostep,88.0,62.0,66,-2,NaN,44.0,182.0,7,5,88.0
47,Te Robar�,Nicky Jam,latin,176.0,75.0,67,-4,8.0,80.0,202.0,24,6,88.0
48,Happier,Marshmello,brostep,100.0,79.0,69,-3,17.0,67.0,214.0,19,5,88.0
49,Call You Mine,The Chainsmokers,edm,104.0,70.0,59,-6,41.0,50.0,218.0,23,3,88.0
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95.0,79.0,75,-6,7.0,61.0,206.0,21,12,82.0

In [60]:
music_df.columns

Index(['Track.Name', 'Artist.Name', 'Genre', 'Beats.Per.Minute', 'Energy',
       'Danceability..db..', 'Loudness..', 'Liveness.', 'Valence ()', 'Length',
       'Acousticness', 'Speechiness', 'Popularity'],
      dtype='object')

In [61]:
music_df.columns = ['name', 'artist', 'genre', 'bpm', 'energy','danceability', 'loudness', 'liveness', 'valence', 'length','acousticness', 'speechiness', 'popularity']
music_df

,name,artist,genre,bpm,energy,danceability,loudness,liveness,valence,length,acousticness,speechiness,popularity
1,Se�orita,Shawn Mendes,canadian pop,117.0,55.0,76,-6,8.0,75.0,191.0,4,3,79.0
2,China,Anuel AA,reggaeton flow,105.0,81.0,79,-4,8.0,61.0,302.0,8,9,92.0
3,boyfriend (with Social House),Ariana Grande,dance pop,190.0,80.0,40,-4,16.0,70.0,186.0,12,46,85.0
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93.0,65.0,64,-8,8.0,55.0,198.0,12,19,86.0
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,NaN,65.0,58,-4,11.0,18.0,175.0,45,7,94.0
6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102.0,68.0,80,-5,9.0,84.0,220.0,9,4,84.0
7,Ransom,Lil Tecca,trap music,180.0,64.0,75,-6,7.0,NaN,131.0,2,29,92.0
8,How Do You Sleep?,Sam Smith,pop,111.0,68.0,48,-5,8.0,35.0,202.0,15,9,90.0
9,Old Town Road - Remix,Lil Nas X,country rap,136.0,62.0,88,-6,11.0,64.0,157.0,5,10,87.0
10,bad guy,Billie Eilish,electropop,135.0,43.0,70,-11,10.0,56.0,194.0,33,38,95.0
11,Callaita,Bad Bunny,reggaeton,176.0,62.0,61,-5,24.0,24.0,NaN,60,31,93.0
12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96.0,71.0,82,-4,15.0,38.0,185.0,28,7,NaN
13,Someone You Loved,Lewis Capaldi,pop,110.0,41.0,50,-6,11.0,45.0,182.0,75,3,88.0
14,Otro Trago - Remix,Sech,panamanian pop,176.0,79.0,73,-2,6.0,76.0,288.0,7,20,87.0
15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101.0,50.0,83,-4,12.0,10.0,205.0,10,5,92.0
16,No Guidance (feat. Drake),Chris Brown,dance pop,93.0,45.0,70,-7,16.0,14.0,261.0,12,15,82.0
17,LA CANCI�N,J Balvin,latin,176.0,65.0,75,-6,11.0,43.0,243.0,15,32,90.0
18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90.0,48.0,76,-6,7.0,91.0,158.0,56,5,91.0
19,Lalala,Y2K,canadian hip hop,130.0,39.0,84,-8,14.0,50.0,161.0,18,8,88.0
20,Truth Hurts,Lizzo,escape room,158.0,62.0,72,-3,12.0,41.0,NaN,11,11,91.0
21,Piece Of Your Heart,MEDUZA,pop house,124.0,74.0,68,-7,7.0,63.0,153.0,4,3,91.0
22,Panini,Lil Nas X,country rap,154.0,59.0,70,-6,12.0,48.0,115.0,34,8,91.0
23,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92.0,79.0,81,-4,9.0,58.0,309.0,14,7,83.0
24,Soltera - Remix,Lunay,latin,92.0,78.0,80,-4,44.0,80.0,266.0,36,4,91.0
25,bad guy (with Justin Bieber),Billie Eilish,electropop,135.0,45.0,67,-11,12.0,68.0,195.0,25,30,89.0
26,If I Can't Have You,Shawn Mendes,canadian pop,NaN,82.0,69,-4,NaN,87.0,191.0,49,6,70.0
27,Dance Monkey,Tones and I,australian pop,98.0,59.0,82,-6,18.0,54.0,210.0,69,10,83.0
28,It's You,Ali Gatie,canadian hip hop,96.0,46.0,73,-7,19.0,40.0,213.0,37,3,89.0
29,Con Calma,Daddy Yankee,latin,94.0,86.0,74,-3,6.0,66.0,193.0,11,6,91.0
30,QUE PRETENDES,J Balvin,latin,93.0,NaN,64,-4,36.0,94.0,222.0,3,25,89.0
31,Takeaway,The Chainsmokers,edm,85.0,51.0,29,-8,10.0,36.0,210.0,12,4,84.0
32,7 rings,Ariana Grande,dance pop,140.0,32.0,78,-11,9.0,33.0,179.0,59,33,89.0
33,0.958333333333333,Maluma,reggaeton,96.0,71.0,78,-5,9.0,68.0,176.0,22,28,89.0
34,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98.0,59.0,80,-7,13.0,18.0,200.0,2,15,89.0
35,Never Really Over,Katy Perry,dance pop,100.0,88.0,77,-5,32.0,39.0,NaN,19,6,89.0
36,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114.0,72.0,66,-7,14.0,32.0,164.0,18,6,89.0
37,Otro Trago,Sech,panamanian pop,176.0,70.0,75,-5,11.0,62.0,226.0,14,34,91.0
38,Antisocial (with Travis Scott),Ed Sheeran,pop,152.0,82.0,72,-5,36.0,91.0,162.0,13,5,87.0
39,Sucker,Jonas Brothers,boy band,138.0,73.0,84,-5,11.0,95.0,181.0,4,6,80.0
40,"fuck, i'm lonely (with Anne-Marie) - from �13 ...",Lauv,dance pop,95.0,56.0,81,-6,6.0,68.0,199.0,48,7,78.0
41,Higher Love,Kygo,edm,104.0,68.0,69,-7,10.0,40.0,228.0,2,3,88.0
42,You Need To Calm Down,Taylor Swift,dance pop,85.0,68.0,77,-6,7.0,73.0,171.0,1,5,90.0
43,Shallow,Lady Gaga,dance pop,96.0,39.0,57,-6,23.0,32.0,216.0,37,3,87.0
44,Talk,Khalid,pop,136.0,40.0,90,-9,6.0,35.0,198.0,5,13,84.0
45,Con Altura,ROSAL�A,r&b en espanol,98.0,69.0,88,-4,5.0,75.0,162.0,39,12,88.0
46,One Thing Right,Marshmello,brostep,88.0,62.0,66,-2,NaN,44.0,182.0,7,5,88.0
47,Te Robar�,Nicky Jam,latin,176.0,75.0,67,-4,8.0,80.0,202.0,24,6,88.0
48,Happier,Marshmello,brostep,100.0,79.0,69,-3,17.0,67.0,214.0,19,5,88.0
49,Call You Mine,The Chainsmokers,edm,104.0,70.0,59,-6,41.0,50.0,218.0,23,3,88.0
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95.0,79.0,75,-6,7.0,61.0,206.0,21,12,82.0

In [62]:
music_df.info

<bound method DataFrame.info of                                                  name            artist  \
1                                            Se�orita      Shawn Mendes
2                                               China          Anuel AA
3                       boyfriend (with Social House)     Ariana Grande
4                     Beautiful People (feat. Khalid)        Ed Sheeran
5                         Goodbyes (Feat. Young Thug)       Post Malone
6                   I Don't Care (with Justin Bieber)        Ed Sheeran
7                                              Ransom         Lil Tecca
8                                   How Do You Sleep?         Sam Smith
9                               Old Town Road - Remix         Lil Nas X
10                                            bad guy     Billie Eilish
11                                           Callaita         Bad Bunny
12              Loco Contigo (feat. J. Balvin & Tyga)          DJ Snake
13                                  Someone You Loved     Lewis Capaldi
14                                 Otro Trago - Remix              Sech
15           Money In The Grave (Drake ft. Rick Ross)             Drake
16                          No Guidance (feat. Drake)       Chris Brown
17                                         LA CANCI�N          J Balvin
18      Sunflower - Spider-Man: Into the Spider-Verse       Post Malone
19                                             Lalala               Y2K
20                                        Truth Hurts             Lizzo
21                                Piece Of Your Heart            MEDUZA
22                                             Panini         Lil Nas X
23                               No Me Conoce - Remix       Jhay Cortez
24                                    Soltera - Remix             Lunay
25                       bad guy (with Justin Bieber)     Billie Eilish
26                                If I Can't Have You      Shawn Mendes
27                                       Dance Monkey       Tones and I
28                                           It's You         Ali Gatie
29                                          Con Calma      Daddy Yankee
30                                      QUE PRETENDES          J Balvin
31                                           Takeaway  The Chainsmokers
32                                            7 rings     Ariana Grande
33                                  0.958333333333333            Maluma
34          The London (feat. J. Cole & Travis Scott)        Young Thug
35                                  Never Really Over        Katy Perry
36  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix
37                                         Otro Trago              Sech
38                     Antisocial (with Travis Scott)        Ed Sheeran
39                                             Sucker    Jonas Brothers
40  fuck, i'm lonely (with Anne-Marie) - from �13 ...              Lauv
41                                        Higher Love              Kygo
42                              You Need To Calm Down      Taylor Swift
43                                            Shallow         Lady Gaga
44                                               Talk            Khalid
45                                         Con Altura           ROSAL�A
46                                    One Thing Right        Marshmello
47                                          Te Robar�         Nicky Jam
48                                            Happier        Marshmello
49                                      Call You Mine  The Chainsmokers
50      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran

               genre    bpm  energy  danceability  loudness  liveness  \
1       canadian pop  117.0    55.0            76        -6       8.0
2     reggaeton flow  105.0    81.0            79        -4       8.0
3          dance pop  190.0    80.0            40        -4      16.0
4                pop   93.0    65.0            64        -8       8.0
5            dfw rap    NaN    65.0            58        -4      11.0
6                pop  102.0    68.0            80        -5       9.0
7         trap music  180.0    64.0            75        -6       7.0
8                pop  111.0    68.0            48        -5       8.0
9        country rap  136.0    62.0            88        -6      11.0
10        electropop  135.0    43.0            70       -11      10.0
11         reggaeton  176.0    62.0            61        -5      24.0
12         dance pop   96.0    71.0            82        -4      15.0
13               pop  110.0    41.0            50        -6      11.0
14    panamanian pop  176.0    79.0            73        -2       6.0
15  canadian hip hop  101.0    50.0            83        -4      12.0
16         dance pop   93.0    45.0            70        -7      16.0
17             latin  176.0    65.0            75        -6      11.0
18           dfw rap   90.0    48.0            76        -6       7.0
19  canadian hip hop  130.0    39.0            84        -8      14.0
20       escape room  158.0    62.0            72        -3      12.0
21         pop house  124.0    74.0            68        -7       7.0
22       country rap  154.0    59.0            70        -6      12.0
23    reggaeton flow   92.0    79.0            81        -4       9.0
24             latin   92.0    78.0            80        -4      44.0
25        electropop  135.0    45.0            67       -11      12.0
26      canadian pop    NaN    82.0            69        -4       NaN
27    australian pop   98.0    59.0            82        -6      18.0
28  canadian hip hop   96.0    46.0            73        -7      19.0
29             latin   94.0    86.0            74        -3       6.0
30             latin   93.0     NaN            64        -4      36.0
31               edm   85.0    51.0            29        -8      10.0
32         dance pop  140.0    32.0            78       -11       9.0
33         reggaeton   96.0    71.0            78        -5       9.0
34       atl hip hop   98.0    59.0            80        -7      13.0
35         dance pop  100.0    88.0            77        -5      32.0
36          big room  114.0    72.0            66        -7      14.0
37    panamanian pop  176.0    70.0            75        -5      11.0
38               pop  152.0    82.0            72        -5      36.0
39          boy band  138.0    73.0            84        -5      11.0
40         dance pop   95.0    56.0            81        -6       6.0
41               edm  104.0    68.0            69        -7      10.0
42         dance pop   85.0    68.0            77        -6       7.0
43         dance pop   96.0    39.0            57        -6      23.0
44               pop  136.0    40.0            90        -9       6.0
45    r&b en espanol   98.0    69.0            88        -4       5.0
46           brostep   88.0    62.0            66        -2       NaN
47             latin  176.0    75.0            67        -4       8.0
48           brostep  100.0    79.0            69        -3      17.0
49               edm  104.0    70.0            59        -6      41.0
50               pop   95.0    79.0            75        -6       7.0

    valence  length  acousticness  speechiness  popularity
1      75.0   191.0             4            3        79.0
2      61.0   302.0             8            9        92.0
3      70.0   186.0            12           46        85.0
4      55.0   198.0            12           19        86.0
5      18.0   175.0            45            7        94.0
6      84.0   220.0             9            4        84.0
7       NaN   131.0             2           29        92.0
8      35.0   202.0            15            9        90.0
9      64.0   157.0             5           10        87.0
10     56.0   194.0            33           38        95.0
11     24.0     NaN            60           31        93.0
12     38.0   185.0            28            7         NaN
13     45.0   182.0            75            3        88.0
14     76.0   288.0             7           20        87.0
15     10.0   205.0            10            5        92.0
16     14.0   261.0            12           15        82.0
17     43.0   243.0            15           32        90.0
18     91.0   158.0            56            5        91.0
19     50.0   161.0            18            8        88.0
20     41.0     NaN            11           11        91.0
21     63.0   153.0             4            3        91.0
22     48.0   115.0            34            8        91.0
23     58.0   309.0            14            7        83.0
24     80.0   266.0            36            4        91.0
25     68.0   195.0            25           30        89.0
26     87.0   191.0            49            6        70.0
27     54.0   210.0            69           10        83.0
28     40.0   213.0            37            3        89.0
29     66.0   193.0            11            6        91.0
30     94.0   222.0             3           25        89.0
31     36.0   210.0            12            4        84.0
32     33.0   179.0            59           33        89.0
33     68.0   176.0            22           28        89.0
34     18.0   200.0             2           15        89.0
35     39.0     NaN            19            6        89.0
36     32.0   164.0            18            6        89.0
37     62.0   226.0            14           34        91.0
38     91.0   162.0            13            5        87.0
39     95.0   181.0             4            6        80.0
40     68.0   199.0            48            7        78.0
41     40.0   228.0             2            3        88.0
42     73.0   171.0             1            5        90.0
43     32.0   216.0            37            3        87.0
44     35.0   198.0             5           13        84.0
45     75.0   162.0            39           12        88.0
46     44.0   182.0             7            5        88.0
47     80.0   202.0            24            6        88.0
48     67.0   214.0            19            5        88.0
49     50.0   218.0            23            3        88.0
50     61.0   206.0            21           12        82.0  >

In [63]:
music_df.fillna(music_df.mean())

,name,artist,genre,bpm,energy,danceability,loudness,liveness,valence,length,acousticness,speechiness,popularity
1,Se�orita,Shawn Mendes,canadian pop,117.000000,55.000000,76,-6,8.000000,75.000000,191.0,4,3,79.000000
2,China,Anuel AA,reggaeton flow,105.000000,81.000000,79,-4,8.000000,61.000000,302.0,8,9,92.000000
3,boyfriend (with Social House),Ariana Grande,dance pop,190.000000,80.000000,40,-4,16.000000,70.000000,186.0,12,46,85.000000
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93.000000,65.000000,64,-8,8.000000,55.000000,198.0,12,19,86.000000
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,119.354167,65.000000,58,-4,11.000000,18.000000,175.0,45,7,94.000000
6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102.000000,68.000000,80,-5,9.000000,84.000000,220.0,9,4,84.000000
7,Ransom,Lil Tecca,trap music,180.000000,64.000000,75,-6,7.000000,55.244898,131.0,2,29,92.000000
8,How Do You Sleep?,Sam Smith,pop,111.000000,68.000000,48,-5,8.000000,35.000000,202.0,15,9,90.000000
9,Old Town Road - Remix,Lil Nas X,country rap,136.000000,62.000000,88,-6,11.000000,64.000000,157.0,5,10,87.000000
10,bad guy,Billie Eilish,electropop,135.000000,43.000000,70,-11,10.000000,56.000000,194.0,33,38,95.000000
11,Callaita,Bad Bunny,reggaeton,176.000000,62.000000,61,-5,24.000000,24.000000,200.0,60,31,93.000000
12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96.000000,71.000000,82,-4,15.000000,38.000000,185.0,28,7,87.530612
13,Someone You Loved,Lewis Capaldi,pop,110.000000,41.000000,50,-6,11.000000,45.000000,182.0,75,3,88.000000
14,Otro Trago - Remix,Sech,panamanian pop,176.000000,79.000000,73,-2,6.000000,76.000000,288.0,7,20,87.000000
15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101.000000,50.000000,83,-4,12.000000,10.000000,205.0,10,5,92.000000
16,No Guidance (feat. Drake),Chris Brown,dance pop,93.000000,45.000000,70,-7,16.000000,14.000000,261.0,12,15,82.000000
17,LA CANCI�N,J Balvin,latin,176.000000,65.000000,75,-6,11.000000,43.000000,243.0,15,32,90.000000
18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90.000000,48.000000,76,-6,7.000000,91.000000,158.0,56,5,91.000000
19,Lalala,Y2K,canadian hip hop,130.000000,39.000000,84,-8,14.000000,50.000000,161.0,18,8,88.000000
20,Truth Hurts,Lizzo,escape room,158.000000,62.000000,72,-3,12.000000,41.000000,200.0,11,11,91.000000
21,Piece Of Your Heart,MEDUZA,pop house,124.000000,74.000000,68,-7,7.000000,63.000000,153.0,4,3,91.000000
22,Panini,Lil Nas X,country rap,154.000000,59.000000,70,-6,12.000000,48.000000,115.0,34,8,91.000000
23,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92.000000,79.000000,81,-4,9.000000,58.000000,309.0,14,7,83.000000
24,Soltera - Remix,Lunay,latin,92.000000,78.000000,80,-4,44.000000,80.000000,266.0,36,4,91.000000
25,bad guy (with Justin Bieber),Billie Eilish,electropop,135.000000,45.000000,67,-11,12.000000,68.000000,195.0,25,30,89.000000
26,If I Can't Have You,Shawn Mendes,canadian pop,119.354167,82.000000,69,-4,13.791667,87.000000,191.0,49,6,70.000000
27,Dance Monkey,Tones and I,australian pop,98.000000,59.000000,82,-6,18.000000,54.000000,210.0,69,10,83.000000
28,It's You,Ali Gatie,canadian hip hop,96.000000,46.000000,73,-7,19.000000,40.000000,213.0,37,3,89.000000
29,Con Calma,Daddy Yankee,latin,94.000000,86.000000,74,-3,6.000000,66.000000,193.0,11,6,91.000000
30,QUE PRETENDES,J Balvin,latin,93.000000,63.755102,64,-4,36.000000,94.000000,222.0,3,25,89.000000
31,Takeaway,The Chainsmokers,edm,85.000000,51.000000,29,-8,10.000000,36.000000,210.0,12,4,84.000000
32,7 rings,Ariana Grande,dance pop,140.000000,32.000000,78,-11,9.000000,33.000000,179.0,59,33,89.000000
33,0.958333333333333,Maluma,reggaeton,96.000000,71.000000,78,-5,9.000000,68.000000,176.0,22,28,89.000000
34,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98.000000,59.000000,80,-7,13.000000,18.000000,200.0,2,15,89.000000
35,Never Really Over,Katy Perry,dance pop,100.000000,88.000000,77,-5,32.000000,39.000000,200.0,19,6,89.000000
36,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114.000000,72.000000,66,-7,14.000000,32.000000,164.0,18,6,89.000000
37,Otro Trago,Sech,panamanian pop,176.000000,70.000000,75,-5,11.000000,62.000000,226.0,14,34,91.000000
38,Antisocial (with Travis Scott),Ed Sheeran,pop,152.000000,82.000000,72,-5,36.000000,91.000000,162.0,13,5,87.000000
39,Sucker,Jonas Brothers,boy band,138.000000,73.000000,84,-5,11.000000,95.000000,181.0,4,6,80.000000
40,"fuck, i'm lonely (with Anne-Marie) - from �13 ...",Lauv,dance pop,95.000000,56.000000,81,-6,6.000000,68.000000,199.0,48,7,78.000000
41,Higher Love,Kygo,edm,104.000000,68.000000,69,-7,10.000000,40.000000,228.0,2,3,88.000000
42,You Need To Calm Down,Taylor Swift,dance pop,85.000000,68.000000,77,-6,7.000000,73.000000,171.0,1,5,90.000000
43,Shallow,Lady Gaga,dance pop,96.000000,39.000000,57,-6,23.000000,32.000000,216.0,37,3,87.000000
44,Talk,Khalid,pop,136.000000,40.000000,90,-9,6.000000,35.000000,198.0,5,13,84.000000
45,Con Altura,ROSAL�A,r&b en espanol,98.000000,69.000000,88,-4,5.000000,75.000000,162.0,39,12,88.000000
46,One Thing Right,Marshmello,brostep,88.000000,62.000000,66,-2,13.791667,44.000000,182.0,7,5,88.000000
47,Te Robar�,Nicky Jam,latin,176.000000,75.000000,67,-4,8.000000,80.000000,202.0,24,6,88.000000
48,Happier,Marshmello,brostep,100.000000,79.000000,69,-3,17.000000,67.000000,214.0,19,5,88.000000
49,Call You Mine,The Chainsmokers,edm,104.000000,70.000000,59,-6,41.000000,50.000000,218.0,23,3,88.000000
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95.000000,79.000000,75,-6,7.000000,61.000000,206.0,21,12,82.000000

In [64]:
music_df.fillna(music_df.median())

,name,artist,genre,bpm,energy,danceability,loudness,liveness,valence,length,acousticness,speechiness,popularity
1,Se�orita,Shawn Mendes,canadian pop,117.0,55.0,76,-6,8.0,75.0,191.0,4,3,79.0
2,China,Anuel AA,reggaeton flow,105.0,81.0,79,-4,8.0,61.0,302.0,8,9,92.0
3,boyfriend (with Social House),Ariana Grande,dance pop,190.0,80.0,40,-4,16.0,70.0,186.0,12,46,85.0
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93.0,65.0,64,-8,8.0,55.0,198.0,12,19,86.0
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,104.0,65.0,58,-4,11.0,18.0,175.0,45,7,94.0
6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102.0,68.0,80,-5,9.0,84.0,220.0,9,4,84.0
7,Ransom,Lil Tecca,trap music,180.0,64.0,75,-6,7.0,56.0,131.0,2,29,92.0
8,How Do You Sleep?,Sam Smith,pop,111.0,68.0,48,-5,8.0,35.0,202.0,15,9,90.0
9,Old Town Road - Remix,Lil Nas X,country rap,136.0,62.0,88,-6,11.0,64.0,157.0,5,10,87.0
10,bad guy,Billie Eilish,electropop,135.0,43.0,70,-11,10.0,56.0,194.0,33,38,95.0
11,Callaita,Bad Bunny,reggaeton,176.0,62.0,61,-5,24.0,24.0,198.0,60,31,93.0
12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96.0,71.0,82,-4,15.0,38.0,185.0,28,7,88.0
13,Someone You Loved,Lewis Capaldi,pop,110.0,41.0,50,-6,11.0,45.0,182.0,75,3,88.0
14,Otro Trago - Remix,Sech,panamanian pop,176.0,79.0,73,-2,6.0,76.0,288.0,7,20,87.0
15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101.0,50.0,83,-4,12.0,10.0,205.0,10,5,92.0
16,No Guidance (feat. Drake),Chris Brown,dance pop,93.0,45.0,70,-7,16.0,14.0,261.0,12,15,82.0
17,LA CANCI�N,J Balvin,latin,176.0,65.0,75,-6,11.0,43.0,243.0,15,32,90.0
18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90.0,48.0,76,-6,7.0,91.0,158.0,56,5,91.0
19,Lalala,Y2K,canadian hip hop,130.0,39.0,84,-8,14.0,50.0,161.0,18,8,88.0
20,Truth Hurts,Lizzo,escape room,158.0,62.0,72,-3,12.0,41.0,198.0,11,11,91.0
21,Piece Of Your Heart,MEDUZA,pop house,124.0,74.0,68,-7,7.0,63.0,153.0,4,3,91.0
22,Panini,Lil Nas X,country rap,154.0,59.0,70,-6,12.0,48.0,115.0,34,8,91.0
23,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92.0,79.0,81,-4,9.0,58.0,309.0,14,7,83.0
24,Soltera - Remix,Lunay,latin,92.0,78.0,80,-4,44.0,80.0,266.0,36,4,91.0
25,bad guy (with Justin Bieber),Billie Eilish,electropop,135.0,45.0,67,-11,12.0,68.0,195.0,25,30,89.0
26,If I Can't Have You,Shawn Mendes,canadian pop,104.0,82.0,69,-4,11.0,87.0,191.0,49,6,70.0
27,Dance Monkey,Tones and I,australian pop,98.0,59.0,82,-6,18.0,54.0,210.0,69,10,83.0
28,It's You,Ali Gatie,canadian hip hop,96.0,46.0,73,-7,19.0,40.0,213.0,37,3,89.0
29,Con Calma,Daddy Yankee,latin,94.0,86.0,74,-3,6.0,66.0,193.0,11,6,91.0
30,QUE PRETENDES,J Balvin,latin,93.0,65.0,64,-4,36.0,94.0,222.0,3,25,89.0
31,Takeaway,The Chainsmokers,edm,85.0,51.0,29,-8,10.0,36.0,210.0,12,4,84.0
32,7 rings,Ariana Grande,dance pop,140.0,32.0,78,-11,9.0,33.0,179.0,59,33,89.0
33,0.958333333333333,Maluma,reggaeton,96.0,71.0,78,-5,9.0,68.0,176.0,22,28,89.0
34,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98.0,59.0,80,-7,13.0,18.0,200.0,2,15,89.0
35,Never Really Over,Katy Perry,dance pop,100.0,88.0,77,-5,32.0,39.0,198.0,19,6,89.0
36,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114.0,72.0,66,-7,14.0,32.0,164.0,18,6,89.0
37,Otro Trago,Sech,panamanian pop,176.0,70.0,75,-5,11.0,62.0,226.0,14,34,91.0
38,Antisocial (with Travis Scott),Ed Sheeran,pop,152.0,82.0,72,-5,36.0,91.0,162.0,13,5,87.0
39,Sucker,Jonas Brothers,boy band,138.0,73.0,84,-5,11.0,95.0,181.0,4,6,80.0
40,"fuck, i'm lonely (with Anne-Marie) - from �13 ...",Lauv,dance pop,95.0,56.0,81,-6,6.0,68.0,199.0,48,7,78.0
41,Higher Love,Kygo,edm,104.0,68.0,69,-7,10.0,40.0,228.0,2,3,88.0
42,You Need To Calm Down,Taylor Swift,dance pop,85.0,68.0,77,-6,7.0,73.0,171.0,1,5,90.0
43,Shallow,Lady Gaga,dance pop,96.0,39.0,57,-6,23.0,32.0,216.0,37,3,87.0
44,Talk,Khalid,pop,136.0,40.0,90,-9,6.0,35.0,198.0,5,13,84.0
45,Con Altura,ROSAL�A,r&b en espanol,98.0,69.0,88,-4,5.0,75.0,162.0,39,12,88.0
46,One Thing Right,Marshmello,brostep,88.0,62.0,66,-2,11.0,44.0,182.0,7,5,88.0
47,Te Robar�,Nicky Jam,latin,176.0,75.0,67,-4,8.0,80.0,202.0,24,6,88.0
48,Happier,Marshmello,brostep,100.0,79.0,69,-3,17.0,67.0,214.0,19,5,88.0
49,Call You Mine,The Chainsmokers,edm,104.0,70.0,59,-6,41.0,50.0,218.0,23,3,88.0
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95.0,79.0,75,-6,7.0,61.0,206.0,21,12,82.0

In [65]:
music_df.dropna()

,name,artist,genre,bpm,energy,danceability,loudness,liveness,valence,length,acousticness,speechiness,popularity
1,Se�orita,Shawn Mendes,canadian pop,117.0,55.0,76,-6,8.0,75.0,191.0,4,3,79.0
2,China,Anuel AA,reggaeton flow,105.0,81.0,79,-4,8.0,61.0,302.0,8,9,92.0
3,boyfriend (with Social House),Ariana Grande,dance pop,190.0,80.0,40,-4,16.0,70.0,186.0,12,46,85.0
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93.0,65.0,64,-8,8.0,55.0,198.0,12,19,86.0
6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102.0,68.0,80,-5,9.0,84.0,220.0,9,4,84.0
8,How Do You Sleep?,Sam Smith,pop,111.0,68.0,48,-5,8.0,35.0,202.0,15,9,90.0
9,Old Town Road - Remix,Lil Nas X,country rap,136.0,62.0,88,-6,11.0,64.0,157.0,5,10,87.0
10,bad guy,Billie Eilish,electropop,135.0,43.0,70,-11,10.0,56.0,194.0,33,38,95.0
13,Someone You Loved,Lewis Capaldi,pop,110.0,41.0,50,-6,11.0,45.0,182.0,75,3,88.0
14,Otro Trago - Remix,Sech,panamanian pop,176.0,79.0,73,-2,6.0,76.0,288.0,7,20,87.0
15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101.0,50.0,83,-4,12.0,10.0,205.0,10,5,92.0
16,No Guidance (feat. Drake),Chris Brown,dance pop,93.0,45.0,70,-7,16.0,14.0,261.0,12,15,82.0
17,LA CANCI�N,J Balvin,latin,176.0,65.0,75,-6,11.0,43.0,243.0,15,32,90.0
18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90.0,48.0,76,-6,7.0,91.0,158.0,56,5,91.0
19,Lalala,Y2K,canadian hip hop,130.0,39.0,84,-8,14.0,50.0,161.0,18,8,88.0
21,Piece Of Your Heart,MEDUZA,pop house,124.0,74.0,68,-7,7.0,63.0,153.0,4,3,91.0
22,Panini,Lil Nas X,country rap,154.0,59.0,70,-6,12.0,48.0,115.0,34,8,91.0
23,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92.0,79.0,81,-4,9.0,58.0,309.0,14,7,83.0
24,Soltera - Remix,Lunay,latin,92.0,78.0,80,-4,44.0,80.0,266.0,36,4,91.0
25,bad guy (with Justin Bieber),Billie Eilish,electropop,135.0,45.0,67,-11,12.0,68.0,195.0,25,30,89.0
27,Dance Monkey,Tones and I,australian pop,98.0,59.0,82,-6,18.0,54.0,210.0,69,10,83.0
28,It's You,Ali Gatie,canadian hip hop,96.0,46.0,73,-7,19.0,40.0,213.0,37,3,89.0
29,Con Calma,Daddy Yankee,latin,94.0,86.0,74,-3,6.0,66.0,193.0,11,6,91.0
31,Takeaway,The Chainsmokers,edm,85.0,51.0,29,-8,10.0,36.0,210.0,12,4,84.0
32,7 rings,Ariana Grande,dance pop,140.0,32.0,78,-11,9.0,33.0,179.0,59,33,89.0
33,0.958333333333333,Maluma,reggaeton,96.0,71.0,78,-5,9.0,68.0,176.0,22,28,89.0
34,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98.0,59.0,80,-7,13.0,18.0,200.0,2,15,89.0
36,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114.0,72.0,66,-7,14.0,32.0,164.0,18,6,89.0
37,Otro Trago,Sech,panamanian pop,176.0,70.0,75,-5,11.0,62.0,226.0,14,34,91.0
38,Antisocial (with Travis Scott),Ed Sheeran,pop,152.0,82.0,72,-5,36.0,91.0,162.0,13,5,87.0
39,Sucker,Jonas Brothers,boy band,138.0,73.0,84,-5,11.0,95.0,181.0,4,6,80.0
40,"fuck, i'm lonely (with Anne-Marie) - from �13 ...",Lauv,dance pop,95.0,56.0,81,-6,6.0,68.0,199.0,48,7,78.0
41,Higher Love,Kygo,edm,104.0,68.0,69,-7,10.0,40.0,228.0,2,3,88.0
42,You Need To Calm Down,Taylor Swift,dance pop,85.0,68.0,77,-6,7.0,73.0,171.0,1,5,90.0
43,Shallow,Lady Gaga,dance pop,96.0,39.0,57,-6,23.0,32.0,216.0,37,3,87.0
44,Talk,Khalid,pop,136.0,40.0,90,-9,6.0,35.0,198.0,5,13,84.0
45,Con Altura,ROSAL�A,r&b en espanol,98.0,69.0,88,-4,5.0,75.0,162.0,39,12,88.0
47,Te Robar�,Nicky Jam,latin,176.0,75.0,67,-4,8.0,80.0,202.0,24,6,88.0
48,Happier,Marshmello,brostep,100.0,79.0,69,-3,17.0,67.0,214.0,19,5,88.0
49,Call You Mine,The Chainsmokers,edm,104.0,70.0,59,-6,41.0,50.0,218.0,23,3,88.0
50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95.0,79.0,75,-6,7.0,61.0,206.0,21,12,82.0

In [100]:
least_pop_song_artist = music_df[music_df['popularity'] == music_df['popularity'].min()].iloc[0]['artist']

In [101]:
least_pop_song_artist

'Shawn Mendes'

In [102]:
artist_folio = music_df[music_df['artist'] == least_pop_song_artist]

In [103]:
artist_folio[artist_folio['loudness']==artist_folio['loudness'].max()]['name']

26    If I Can't Have You
Name: name, dtype: object

In [105]:
names,counts = np.unique(music_df['artist'],return_counts=True)

In [114]:
df2 = pd.DataFrame.from_dict(dict(zip(names,counts)),orient='index')

In [110]:
df2

                  0
Ali Gatie         1
Anuel AA          1
Ariana Grande     2
Bad Bunny         1
Billie Eilish     2
Chris Brown       1
DJ Snake          1
Daddy Yankee      1
Drake             1
Ed Sheeran        4
J Balvin          2
Jhay Cortez       1
Jonas Brothers    1
Katy Perry        1
Khalid            1
Kygo              1
Lady Gaga         1
Lauv              1
Lewis Capaldi     1
Lil Nas X         2
Lil Tecca         1
Lizzo             1
Lunay             1
MEDUZA            1
Maluma            1
Marshmello        2
Martin Garrix     1
Nicky Jam         1
Post Malone       2
ROSAL�A           1
Sam Smith         1
Sech              2
Shawn Mendes      2
Taylor Swift      1
The Chainsmokers  2
Tones and I       1
Y2K               1
Young Thug        1